<a href="https://colab.research.google.com/github/HeHeHuang/MachineLearning/blob/main/MachineLearning_ScikitLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This Tutorial help me to have basic understanding of Machine Learning by using scikit-learn 

## Machine Learning Defination


## Machine Learning Process


### Data Preparation


### Modelling


### Modelling evaluation


## Frequency view & Bayes View


### Linear Regression


### Logistic Regression

sigmiod function 
> with distribution


#### binary classification


In [ ]:
from sklearn.datasets import load_iris
import pandas as pd 
import numpy as np 

In [ ]:
iris = load_iris()

In [ ]:
iris
print(list(iris.keys()))

['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module']


In [ ]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
X = iris['data'][:,3:]
X

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.1],
       [0.1],
       [0.2],
       [0.4],
       [0.4],
       [0.3],
       [0.3],
       [0.3],
       [0.2],
       [0.4],
       [0.2],
       [0.5],
       [0.2],
       [0.2],
       [0.4],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.4],
       [0.1],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.3],
       [0.3],
       [0.2],
       [0.6],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [1.4],
       [1.5],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.6],
       [1. ],
       [1.3],
       [1.4],
       [1. ],
       [1.5],
       [1. ],
       [1.4],
       [1.3],
       [1.4],
       [1.5],
       [1. ],
       [1.5],
       [1.1],
       [1.8],
      

In [ ]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
y= (iris['target']==2).astype(np.int)
y

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.linear_model import LogisticRegression
# multi_class='ovr'   one vs rest: for example, if there are three set data, choose one vs others two , and iteration
binary_classifier = LogisticRegression(solver='sag',max_iter =1000,multi_class='ovr')


In [ ]:
binary_classifier = LogisticRegression(solver='sag',max_iter =1000,multi_class='multinomial')

In [ ]:
binary_classifier.fit(X,y)

LogisticRegression(max_iter=1000, multi_class='multinomial', solver='sag')

In [ ]:
X_new = np.linspace(0,3,1000).reshape(-1,1)
X_new

array([[0.        ],
       [0.003003  ],
       [0.00600601],
       [0.00900901],
       [0.01201201],
       [0.01501502],
       [0.01801802],
       [0.02102102],
       [0.02402402],
       [0.02702703],
       [0.03003003],
       [0.03303303],
       [0.03603604],
       [0.03903904],
       [0.04204204],
       [0.04504505],
       [0.04804805],
       [0.05105105],
       [0.05405405],
       [0.05705706],
       [0.06006006],
       [0.06306306],
       [0.06606607],
       [0.06906907],
       [0.07207207],
       [0.07507508],
       [0.07807808],
       [0.08108108],
       [0.08408408],
       [0.08708709],
       [0.09009009],
       [0.09309309],
       [0.0960961 ],
       [0.0990991 ],
       [0.1021021 ],
       [0.10510511],
       [0.10810811],
       [0.11111111],
       [0.11411411],
       [0.11711712],
       [0.12012012],
       [0.12312312],
       [0.12612613],
       [0.12912913],
       [0.13213213],
       [0.13513514],
       [0.13813814],
       [0.141

In [ ]:
y_proba = binary_classifier.predict_proba(X_new)
y_proba

array([[9.99895740e-01, 1.04259677e-04],
       [9.99893989e-01, 1.06011194e-04],
       [9.99892208e-01, 1.07792133e-04],
       ...,
       [5.85033087e-04, 9.99414967e-01],
       [5.75371724e-04, 9.99424628e-01],
       [5.65869820e-04, 9.99434130e-01]])

In [ ]:
y_new = binary_classifier.predict(X_new)
y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

#### mulitiple classification 
>softmax


with 

### Decision Tree


In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier



In [ ]:
iris = load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
X = iris.data[:, 2:] # petal length and width y = iris.target
y = iris.target
tree_clf = DecisionTreeClassifier(max_depth=2) 
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [ ]:
from sklearn.tree import export_graphviz
export_graphviz( 
    tree_clf,
  out_file=image_path("/content/drive/MyDrive/iris_tree.dot"), 
  feature_names=iris.feature_names[2:],
  class_names=iris.target_names, 
  rounded=True,
            filled=True
        )

NameError: ignored

### SVM
linear
Nonlinear
one sentense to discribe

#### langer 

> try to convert the fomular with s.t. to fomular without s.t.


### Random Tree

### XGboost


### PCA



In [ ]:
import pandas as pd 
import numpy as np
import random as rd
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt



In [ ]:
genes = ['gene'+str(i) for i in range(1,101)]

In [ ]:
genes

['gene1',
 'gene2',
 'gene3',
 'gene4',
 'gene5',
 'gene6',
 'gene7',
 'gene8',
 'gene9',
 'gene10',
 'gene11',
 'gene12',
 'gene13',
 'gene14',
 'gene15',
 'gene16',
 'gene17',
 'gene18',
 'gene19',
 'gene20',
 'gene21',
 'gene22',
 'gene23',
 'gene24',
 'gene25',
 'gene26',
 'gene27',
 'gene28',
 'gene29',
 'gene30',
 'gene31',
 'gene32',
 'gene33',
 'gene34',
 'gene35',
 'gene36',
 'gene37',
 'gene38',
 'gene39',
 'gene40',
 'gene41',
 'gene42',
 'gene43',
 'gene44',
 'gene45',
 'gene46',
 'gene47',
 'gene48',
 'gene49',
 'gene50',
 'gene51',
 'gene52',
 'gene53',
 'gene54',
 'gene55',
 'gene56',
 'gene57',
 'gene58',
 'gene59',
 'gene60',
 'gene61',
 'gene62',
 'gene63',
 'gene64',
 'gene65',
 'gene66',
 'gene67',
 'gene68',
 'gene69',
 'gene70',
 'gene71',
 'gene72',
 'gene73',
 'gene74',
 'gene75',
 'gene76',
 'gene77',
 'gene78',
 'gene79',
 'gene80',
 'gene81',
 'gene82',
 'gene83',
 'gene84',
 'gene85',
 'gene86',
 'gene87',
 'gene88',
 'gene89',
 'gene90',
 'gene91',
 'gene92

In [ ]:
wt = ['wt' +str(i) for i in range(1,6)]
ko = ['ko'+str(i) for i in range(1,6)]

In [ ]:
data = pd.DataFrame(columns = [*wt,*ko],index = genes)
data


wt1  wt2  wt3  wt4  wt5  ko1  ko2  ko3  ko4  ko5
gene1    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene2    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene3    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene4    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene5    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
gene96   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene97   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene98   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene99   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene100  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[100 rows x 10 columns]

In [ ]:
for gene in data.index:
  data.loc[gene,'wt1':'wt5'] = np.random.poisson(lam=rd.randrange(10,1000),size =5)
  data.loc[gene,'ko1':'ko5'] = np.random.poisson(lam=rd.randrange(10,1000),size =5)

In [ ]:
print(data.head())

       wt1  wt2  wt3  wt4  wt5  ko1  ko2  ko3  ko4  ko5
gene1   35   37   44   34   37  146  123  135  139  128
gene2  172  169  189  193  188   94  107  104  108  116
gene3  782  823  812  831  770   26   42   27   31   20
gene4  294  304  317  286  305  809  812  808  804  800
gene5  770  753  768  697  766  529  530  542  575  495


In [ ]:
print(data.shape)

(100, 10)


In [ ]:
 scaled_data = preprocessing.scale(data.T)   # after centering, the average value for each gene will be 0, and after scaling, the standard deviation for the values for each gene will be 1 
 # variation is calculated as (measurements- mean) square / the number of measurements 
 scaled_data

array([[-1.04100109,  0.71536658,  0.94325276, -1.02797567,  1.14318516,
        -1.06790806,  1.56560831,  0.67828184,  0.90366903, -0.9293501 ,
         1.00495873, -0.89250195, -0.67106987, -0.90202861, -0.7519935 ,
         1.06718655,  0.91488854,  0.75903153,  0.98097193,  0.93126138,
        -1.05179001,  1.08291685, -1.45486725, -0.99447716,  0.95907157,
         0.98818849,  1.09895609, -0.17826151,  1.12645292,  1.13856321,
        -1.3002041 , -1.04836599, -1.02232367, -0.84790391,  0.86594562,
         1.01716368, -0.70676761,  0.76829249,  1.30471583, -0.97492439,
        -0.88957293,  0.49691382,  0.94695844, -0.94980807, -0.99717387,
         0.98795256, -1.09580362,  0.88244644,  0.78539796,  1.05258697,
        -1.0587667 ,  1.0852627 , -0.89032812,  0.14116278, -1.00289225,
         1.0652278 , -1.00226437,  0.80614828, -1.15649356,  0.99539003,
         1.80261061,  1.03572393, -0.38812692, -1.26005265,  1.13992462,
         0.96392188, -1.03395692,  1.01752751, -1.0

In [ ]:
 pca = PCA()
 pca.fit(scaled_data)
 pca_data = pca.transform(scaled_data)